### ISSUE TITLE
How to use zoneinfo-outlook registry?

### ISSUE THREAD

**Issue by nishthaGupta** [ical4j/ical4j-zoneinfo-outlook#14]
Can someone, with an example, show how to create VTIMEZONE from zoneinfo-outlook registry. 
I have tried:

final TimeZoneRegistry registry = net.fortuna.ical4j.zoneinfo.outlook.OutlookTimeZoneRegistryFactory.getInstance().createRegistry();
final TimeZone timezone = registry.getTimeZone("Asia/Kolkata");
final VTimeZone tz = timezone.getVTimeZone();

Here is the timezone I got:
BEGIN:VTIMEZONE
TZID:Asia/Kolkata
TZURL:http://tzurl.org/zoneinfo/Asia/Kolkata
X-LIC-LOCATION:Asia/Kolkata
BEGIN:STANDARD
TZOFFSETFROM:+055328
TZOFFSETTO:+055320
TZNAME:HMT
DTSTART:18540628T000000
RDATE:18540628T000000
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+055320
TZOFFSETTO:+052110
TZNAME:MMT
DTSTART:18700101T000000
RDATE:18700101T000000
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+052110
TZOFFSETTO:+0530
TZNAME:IST
DTSTART:19051231T233640
RDATE:19051231T233640
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0530
TZOFFSETTO:+0630
TZNAME:+0630
DTSTART:19410930T233640
RDATE:19410930T233640
RDATE:19420901T000000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0630
TZOFFSETTO:+0530
TZNAME:IST
DTSTART:19420515T000000
RDATE:19420515T000000
RDATE:19451015T000000
END:STANDARD
END:VTIMEZONE

As you can see, it is taking timezone from default registry instead of zoneinfo-outlook one.

**Comment by benfortuna** [comment]
So there are two ways you can create an OutlookTimeZoneRegistryFactory instance. 

The first (and recommended) way is to call `TimeZoneRegistryFactory.getInstance()` as you are doing, but you need to configure the instance type, either by an `ical4j.properties` file or System properties, eg:

`net.fortuna.ical4j.timezone.registry=net.fortuna.ical4j.zoneinfo.outlook.OutlookTimeZoneRegistryFactory`

The second way would be to create a new instance directly (which you are also doing), but call `createRegistry()` rather than `getInstance()`, eg:

`new OutlookTimeZoneRegistryFactory().createRegistry()`

**Comment by nishthaGupta** [comment]
@benfortuna : Thank you so much, it resolved my issue.
